import { BookOpenText, Flame, MoonStar, Sparkles } from "lucide-react";
import { useMemo } from "react";
import { diarySummary, insightData, moods } from "../lib/diary";

export default function InsightsPage({ entries, today }) {
  const summary = useMemo(() => diarySummary(entries, today), [entries, today]);
  const data = useMemo(() => insightData(entries, today), [entries, today]);
  const rated = data.moodSeries.filter((day) => day.score);
  const topMood = [...data.moodMix].sort((left, right) => right.count - left.count)[0];

  return <div className="page-stack insights-page">
    <header className="page-heading"><div><span className="eyebrow">Patterns, not verdicts</span><h1>Insights</h1><p>Signals from your own entries. Unwritten days are never inferred.</p></div></header>
    <section className="metric-grid" aria-label="Diary summary"><article className="metric"><span className="metric-icon"><Flame size={18} /></span><span>Current streak</span><strong>{summary.currentStreak}d</strong><small>best {summary.bestStreak}d</small></article><article className="metric"><span className="metric-icon"><Sparkles size={18} /></span><span>Average mood · 30d</span><strong>{summary.averageMood ? `${summary.averageMood.toFixed(1)} / 5` : "—"}</strong><small>{summary.moodEntries} rated entries</small></article><article className="metric"><span className="metric-icon"><BookOpenText size={18} /></span><span>Words written</span><strong>{summary.totalWords.toLocaleString()}</strong><small>{summary.entries} total entries</small></article><article className="metric"><span className="metric-icon"><MoonStar size={18} /></span><span>Average sleep · 30d</span><strong>{summary.averageSleep ? `${summary.averageSleep.toFixed(1)}h` : "—"}</strong><small>{summary.sleepEntries} self-reports</small></article></section>

    <section className="panel mood-chart-card"><header><div><span className="eyebrow">Mood</span><h2>Last thirty days</h2></div><span>{rated.length} rated {rated.length === 1 ? "day" : "days"}</span></header><div className="mood-chart" role="img" aria-label={rated.length ? `${rated.length} rated days with an average mood of ${summary.averageMood.toFixed(1)} out of 5.` : "No mood ratings in the last 30 days."}>{data.moodSeries.map((day) => <div key={day.date}><span>{day.score || ""}</span><i className={day.score ? "has-value" : ""} style={{ "--height": `${day.score ? (day.score / 5) * 100 : 3}%`, "--mood-color": day.token }} /><small>{day.date.slice(8)}</small></div>)}</div><div className="chart-note">{rated.length ? "Only self-reported moods appear; gaps remain visible." : "Choose a mood in a few entries to reveal a gentle pattern."}</div><details className="data-table"><summary>View mood data</summary><table><thead><tr><th>Date</th><th>Mood</th><th>Score</th></tr></thead><tbody>{data.moodSeries.map((day) => <tr key={day.date}><td>{day.date}</td><td>{day.label}</td><td>{day.score || "Not rated"}</td></tr>)}</tbody></table></details></section>

    <section className="insight-grid"><article className="panel mood-mix"><header><div><span className="eyebrow">Mood mix</span><h2>Rated days</h2></div><span>{rated.length && topMood.count ? `${topMood.label} appears most` : "No ratings yet"}</span></header><div>{[...data.moodMix].reverse().map((mood) => <div key={mood.value}><span><i style={{ "--mood-color": mood.token }} />{mood.label}</span><strong>{mood.count}</strong><em><i style={{ "--mood-color": mood.token, "--width": `${rated.length ? (mood.count / rated.length) * 100 : 0}%` }} /></em><small>{rated.length ? Math.round((mood.count / rated.length) * 100) : 0}%</small></div>)}</div></article><article className="panel weekday-card"><header><div><span className="eyebrow">Rhythm</span><h2>By weekday</h2></div><span>Rated entries only</span></header><div className="weekday-bars">{data.weekdays.map((day) => <div key={day.day}><strong>{day.score ? day.score.toFixed(1) : "—"}</strong><i style={{ "--height": `${day.score ? (day.score / 5) * 100 : 3}%` }} /><small>{day.day}</small><span>{day.count}</span></div>)}</div><details className="data-table"><summary>View weekday data</summary><table><thead><tr><th>Weekday</th><th>Average</th><th>Rated entries</th></tr></thead><tbody>{data.weekdays.map((day) => <tr key={day.day}><td>{day.day}</td><td>{day.score ? day.score.toFixed(1) : "Not available"}</td><td>{day.count}</td></tr>)}</tbody></table></details></article></section>
    <p className="insight-disclaimer">These summaries describe only what you entered. They are not a health assessment.</p>
  </div>;
}

