import { CalendarDays, ChevronRight, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { dateRange, shortDate } from "../lib/dates";
import { moodDetails, moods, wordCount } from "../lib/diary";

export default function TimelinePage({ entries, today, onOpen }) {
  const [search, setSearch] = useState("");
  const days = useMemo(() => dateRange(today, 84), [today]);
  const byDate = useMemo(() => new Map(entries.map((entry) => [entry.entryDate, entry])), [entries]);
  const recent = useMemo(() => entries.filter((entry) => entry.entryDate <= today && (!search.trim() || `${entry.highlight} ${entry.content} ${(entry.tags || []).join(" ")}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))), [entries, search, today]);
  const written = days.filter((day) => byDate.has(day)).length;

  return <div className="page-stack timeline-page">
    <header className="page-heading"><div><span className="eyebrow">Look back gently</span><h1>Timeline</h1><p>Empty days remain neutral. This is a record, not a score.</p></div><span className="window-count"><strong>{written}</strong> of 84 days written</span></header>
    <section className="panel calendar-card"><header><div><span className="section-icon"><CalendarDays size={17} /></span><div><span className="eyebrow">Entry history</span><h2>Last twelve weeks</h2></div></div><div className="mood-scale"><span>Rough</span>{moods.map((mood) => <i key={mood.value} style={{ "--mood-color": mood.token }} />)}<span>Great</span></div></header><div className="calendar-scroll"><div className="diary-calendar" role="img" aria-label={`${written} of the last 84 days contain diary entries.`}>{days.map((day) => { const entry = byDate.get(day); const mood = moodDetails(entry?.mood); return <button type="button" key={day} className={entry ? "has-entry" : ""} style={{ "--mood-color": mood?.token }} title={`${shortDate(day)}: ${entry ? mood?.label || "entry written, mood not rated" : "no entry"}`} aria-label={`${day}, ${entry ? mood?.label || "entry written, mood not rated" : "no entry"}`} onClick={() => onOpen(day)} />; })}</div></div><details className="data-table"><summary>View calendar data</summary><table><thead><tr><th>Date</th><th>Entry</th><th>Mood</th></tr></thead><tbody>{days.map((day) => { const entry = byDate.get(day); return <tr key={day}><td>{day}</td><td>{entry ? "Written" : "Not written"}</td><td>{moodDetails(entry?.mood)?.label || "Not rated"}</td></tr>; })}</tbody></table></details></section>
    <section className="timeline-section"><header><div><span className="eyebrow">Entries</span><h2>Recent writing</h2></div><label className="search-field"><Search size={17} /><span className="sr-only">Search entries</span><input type="search" placeholder="Search entries or tags" value={search} onChange={(event) => setSearch(event.target.value)} /></label></header>{recent.length ? <div className="timeline-list">{recent.map((entry) => { const mood = moodDetails(entry.mood); const date = new Date(`${entry.entryDate}T12:00:00`); return <button type="button" key={entry.entryDate} onClick={() => onOpen(entry.entryDate)} style={{ "--mood-color": mood?.token }}><time dateTime={entry.entryDate}><strong>{new Intl.DateTimeFormat("en-IN", { day: "2-digit" }).format(date)}</strong><span>{new Intl.DateTimeFormat("en-IN", { month: "short" }).format(date)}</span><small>{new Intl.DateTimeFormat("en-IN", { weekday: "short" }).format(date)}</small></time><span className="timeline-mood"><i />{mood?.label || "Unrated"}</span><span className="timeline-copy"><strong>{entry.highlight || entry.content.slice(0, 120) || "A quiet entry"}</strong><small>{wordCount(entry.content).toLocaleString()} words{entry.sleepHours != null ? ` · ${entry.sleepHours}h sleep` : ""}</small></span><ChevronRight size={18} /></button>; })}</div> : <div className="timeline-empty"><strong>{search ? "No matching entries" : "Your timeline is ready"}</strong><span>{search ? "Try a different phrase." : "Write your first entry and it will appear here."}</span></div>}</section>
  </div>;
}

